namespace PPDO.Domain.Entities;

/// <summary>
/// A delivery event — records items physically received against a Purchase Request.
/// One PR can have multiple Delivery records over time (partial deliveries allowed).
///
/// DeliveryRef format: DEL-YYYYMMDD-XXXXX  (5-digit random, Manila timezone UTC+8)
/// Generated by DeliveryService on submission; never editable after creation.
/// Submitting a delivery triggers automatic PR status recalculation.
/// </summary>
public sealed class Delivery
{
    /// <summary>Primary key.</summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Unique delivery reference in the format DEL-YYYYMMDD-XXXXX.
    /// Generated using Manila time (UTC+8). 5-digit random suffix.
    /// </summary>
    public string DeliveryRef { get; set; } = string.Empty;

    /// <summary>FK to the Purchase Request this delivery is against.</summary>
    public Guid PRId { get; set; }

    /// <summary>Date the items were physically received (Manila date).</summary>
    public DateOnly DeliveryDate { get; set; }

    /// <summary>Name of the staff member who received the delivery.</summary>
    public string ReceivedBy { get; set; } = string.Empty;

    /// <summary>Name of the supplier / vendor. Optional.</summary>
    public string? Supplier { get; set; }

    /// <summary>Optional remarks / notes about this delivery.</summary>
    public string? Remarks { get; set; }

    // ── Audit ─────────────────────────────────────────────────────────────────

    public DateTime CreatedAt { get; set; }

    // ── Navigation ────────────────────────────────────────────────────────────

    /// <summary>The Purchase Request this delivery is recorded against.</summary>
    public PurchaseRequest? PurchaseRequest { get; set; }

    /// <summary>Individual item lines within this delivery event.</summary>
    public ICollection<DeliveryItem> Items { get; set; } = new List<DeliveryItem>();
}
