using PPDO.Domain.Enums;

namespace PPDO.Domain.Entities;

/// <summary>
/// A formal request for office supplies submitted by a PPDO staff member.
/// Represents the PR form used in the Google Sheets v0.4 system.
///
/// PR No. format: 101-1041-GF-YYYY-MM-DD-XXX  (3-digit zero-padded sequence)
/// Status transitions: Open → PartiallyDelivered → FullyDelivered
/// TotalAmount is computed from the sum of PRItem.TotalCost values.
/// </summary>
public sealed class PurchaseRequest
{
    /// <summary>Primary key.</summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Unique PR number in the format 101-1041-GF-YYYY-MM-DD-XXX.
    /// Generated by PurchaseRequestService on creation; never editable after creation.
    /// </summary>
    public string PRNo { get; set; } = string.Empty;

    /// <summary>Date shown on the physical PR form (not the system creation date).</summary>
    public DateOnly PRDate { get; set; }

    /// <summary>Date and time the record was created in the system (UTC). Auto-set on creation.</summary>
    public DateTime DateCreated { get; set; }

    /// <summary>Requesting department. Defaults to "PPDO".</summary>
    public string Department { get; set; } = "PPDO";

    /// <summary>Division that is requesting the items. Used for division-scope enforcement.</summary>
    public Division Division { get; set; }

    /// <summary>Funding source. e.g. "General Fund".</summary>
    public string Fund { get; set; } = string.Empty;

    /// <summary>Name of the staff member requesting the items.</summary>
    public string RequestedBy { get; set; } = string.Empty;

    /// <summary>Position/title of the requesting staff member.</summary>
    public string Position { get; set; } = string.Empty;

    /// <summary>Name of the approving officer. Optional.</summary>
    public string? ApprovedBy { get; set; }

    /// <summary>Position/title of the approving officer. Optional.</summary>
    public string? ApprovingPosition { get; set; }

    /// <summary>Annual Investment Program code. Optional.</summary>
    public string? AIPCode { get; set; }

    /// <summary>Chart of accounts number. Optional.</summary>
    public string? AccountNo { get; set; }

    /// <summary>Chart of accounts title. Optional.</summary>
    public string? AccountTitle { get; set; }

    /// <summary>
    /// Program name. Long text — up to 120 characters.
    /// Displayed as a textarea (min-height 44px, max-height 88px, resize vertical) in the UI.
    /// </summary>
    public string? Program { get; set; }

    /// <summary>
    /// Project name. Long text — up to 120 characters.
    /// Displayed as a textarea (min-height 44px, max-height 88px, resize vertical) in the UI.
    /// </summary>
    public string? Project { get; set; }

    /// <summary>
    /// Activity name. Long text — up to 120 characters.
    /// Displayed as a textarea (min-height 44px, max-height 88px, resize vertical) in the UI.
    /// </summary>
    public string? Activity { get; set; }

    /// <summary>SAOB/SAOB Inspection number. Optional.</summary>
    public string? SAINo { get; set; }

    /// <summary>ALOBS number. Optional.</summary>
    public string? ALOBSNo { get; set; }

    /// <summary>
    /// Total amount in Philippine Peso (₱). Computed as the sum of all PRItem.TotalCost values.
    /// Updated by PurchaseRequestService whenever items are modified.
    /// </summary>
    public decimal TotalAmount { get; set; }

    /// <summary>Current lifecycle status. Updated automatically by DeliveryService on delivery submission.</summary>
    public PRStatus Status { get; set; } = PRStatus.Open;

    /// <summary>FK to the User who created this PR record.</summary>
    public Guid CreatedById { get; set; }

    // ── Audit ─────────────────────────────────────────────────────────────────

    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }

    // ── Navigation ────────────────────────────────────────────────────────────

    /// <summary>The user who submitted this PR.</summary>
    public User? CreatedBy { get; set; }

    /// <summary>Line items on this PR (Section 2 of the PR form).</summary>
    public ICollection<PRItem> Items { get; set; } = new List<PRItem>();

    /// <summary>Delivery events recorded against this PR.</summary>
    public ICollection<Delivery> Deliveries { get; set; } = new List<Delivery>();
}
