#!/usr/bin/env python3
"""
Generate the CC typology seed SQL from the finalized CSV (PPDO-139).

The list is the LGU typology — JMC 2015-01 (DBM-CCC-DILG) Annex A, which is what the province's
AIP is tagged against. ⚠️ NOT JMC 2013-01 (national agencies): the two reuse the same code numbers
with different meanings, so the lists cannot share this table. The 2013 list is kept for reference
only, unseeded, at docs/v1.8/seed/reference/cc_typologies_jmc2013-01_nga.csv.

    python scripts/cc_typologies_seed.py

Reads   docs/v1.8/seed/cc_typologies_seed.csv   (code,name,category,description,is_active —
        the same columns the config page's CSV import takes)
Writes  backend/PPDO.Infrastructure/Data/Migrations/20260929000622_SeedClimateChangeTypologies.Data.cs

The output is one T-SQL MERGE keyed on `code`:
  * matched      -> name, category, description, is_active overwritten from the CSV
                    (the CSV is the source of truth — config-page edits made before deploy are lost)
  * not in table -> inserted
  * not in CSV and no AIP activity or LDIP program carries it -> deleted
                    (clutter, e.g. a 2013-01 list imported through the config page)
  * not in CSV but still carried somewhere -> kept, set inactive, with the name reset to
                    the code itself: it leaves the pickers, and no activity shows a meaning the
                    LGU typology does not give it (e.g. a 2013-01 title imported on UAT)

⚠️ Regenerate only while the migration is unapplied everywhere. Once it has run on UAT or
production, a changed list needs a NEW migration — never edit an applied one.
"""
import csv
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / 'docs' / 'v1.8' / 'seed' / 'cc_typologies_seed.csv'
OUT_PATH = (ROOT / 'backend' / 'PPDO.Infrastructure' / 'Data' / 'Migrations'
            / '20260929000622_SeedClimateChangeTypologies.Data.cs')

CODE_RE = re.compile(r'[AM]\d{3,4}-\d{2}')
CATEGORIES = {'Adaptation', 'Mitigation'}
NAME_MAX = 500  # ClimateChangeTypology.NameMaxLength
NOT_IN_LIST = 'Not in JMC 2015-01 Annex A (LGU typology).'


def sql_str(value: str) -> str:
    """An N'' literal: single quotes doubled for T-SQL, double quotes doubled for the C# @"" string."""
    return "N'" + value.replace("'", "''").replace('"', '""') + "'"


def load_rows() -> list[dict]:
    with open(CSV_PATH, encoding='utf-8-sig', newline='') as f:
        rows = list(csv.DictReader(f))

    seen: set[str] = set()
    for i, r in enumerate(rows, start=2):  # row 1 is the header
        code, name = r['code'].strip(), r['name'].strip()
        where = f'{CSV_PATH.name} line {i} ({code})'
        if not CODE_RE.fullmatch(code):
            raise SystemExit(f'{where}: code does not look like a CCET code')
        if code in seen:
            raise SystemExit(f'{where}: duplicate code')
        seen.add(code)
        if not name or len(name) > NAME_MAX:
            raise SystemExit(f'{where}: name is empty or over {NAME_MAX} characters')
        if r['category'] not in CATEGORIES:
            raise SystemExit(f'{where}: category must be Adaptation or Mitigation')
        if r['category'][0] != code[0]:
            raise SystemExit(f'{where}: category does not match the code letter')
        if r['is_active'].upper() not in ('TRUE', 'FALSE'):
            raise SystemExit(f'{where}: is_active must be TRUE or FALSE')
    return rows


def main() -> None:
    rows = load_rows()
    values = ',\n'.join(
        '    ({}, {}, {}, {}, {})'.format(
            sql_str(r['code'].strip()),
            sql_str(r['name'].strip()),
            sql_str(r['category']),
            sql_str(r['description'].strip()) if r['description'].strip() else 'NULL',
            1 if r['is_active'].upper() == 'TRUE' else 0)
        for r in rows)

    codes = ',\n'.join(f'        ({sql_str(r["code"].strip())})' for r in rows)

    OUT_PATH.write_text(f'''// <auto-generated>
// Generated by scripts/cc_typologies_seed.py from docs/v1.8/seed/cc_typologies_seed.csv.
// Do not edit by hand — change the CSV and re-run the script ({len(rows)} rows).
// </auto-generated>

namespace PPDO.Infrastructure.Data.Migrations
{{
    public partial class SeedClimateChangeTypologies
    {{
        private const string MergeSql = @"
-- Codes some AIP activity or LDIP program carries. Free text, possibly several per field,
-- separated by commas, semicolons or line breaks.
WITH used AS (
    SELECT DISTINCT UPPER(LTRIM(RTRIM(x.value))) AS code
    FROM (SELECT cc_typology_code AS v FROM aip_activities WHERE cc_typology_code IS NOT NULL
          UNION ALL
          SELECT cc_typology_code FROM ldip_programs WHERE cc_typology_code IS NOT NULL) AS f
    CROSS APPLY STRING_SPLIT(REPLACE(REPLACE(REPLACE(f.v, ';', ','), CHAR(13), ','), CHAR(10), ','), ',') AS x
)
DELETE t
FROM climate_change_typologies AS t
WHERE t.code NOT IN (SELECT code FROM (VALUES
{codes}
    ) AS keep (code))
  AND t.code NOT IN (SELECT code FROM used WHERE code <> N'');

MERGE climate_change_typologies AS t
USING (VALUES
{values}
) AS s (code, name, category, description, is_active)
ON t.code = s.code
WHEN MATCHED AND (
       t.name COLLATE Latin1_General_BIN2 <> s.name
    OR t.category <> s.category
    OR ISNULL(t.description, N'') COLLATE Latin1_General_BIN2 <> ISNULL(s.description, N'')
    OR t.is_active <> s.is_active)
    THEN UPDATE SET name = s.name, category = s.category, description = s.description,
                    is_active = s.is_active, updated_at = GETUTCDATE()
WHEN NOT MATCHED BY TARGET
    THEN INSERT (code, name, category, description, is_active, created_at, updated_at)
         VALUES (s.code, s.name, s.category, s.description, s.is_active, GETUTCDATE(), GETUTCDATE())
WHEN NOT MATCHED BY SOURCE AND (
       t.is_active = 1
    OR t.name COLLATE Latin1_General_BIN2 <> t.code
    OR ISNULL(t.description, N'') COLLATE Latin1_General_BIN2 <> N'{NOT_IN_LIST}')
    THEN UPDATE SET is_active = 0, name = t.code, description = N'{NOT_IN_LIST}',
                    updated_at = GETUTCDATE();";
    }}
}}
''', encoding='utf-8', newline='\n')
    print(f'Wrote {OUT_PATH.relative_to(ROOT)} - {len(rows)} rows, '
          f'{sum(r["is_active"].upper() == "TRUE" for r in rows)} active')


if __name__ == '__main__':
    main()
